name: Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Build
        run: .\C#\build.bat
